"""add support request workflow

Revision ID: 54a7192c8409
Revises: c6e6c2a36199
Create Date: 2026-07-11 20:15:44.065540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a7192c8409'
down_revision: Union[str, Sequence[str], None] = 'c6e6c2a36199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_agent_id', sa.Integer(), nullable=False),
    sa.Column('supporting_agent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('operations_owner', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type IN ('provider_float', 'physical_cash')", name='ck_support_requests_resource_type'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'escalated', 'resolved', 'cancelled')", name='ck_support_requests_status'),
    sa.CheckConstraint("transaction_type IN ('cash_in', 'cash_out')", name='ck_support_requests_transaction_type'),
    sa.CheckConstraint('approved_amount IS NULL OR approved_amount <= requested_amount', name='ck_support_requests_approved_not_above_requested'),
    sa.CheckConstraint('approved_amount IS NULL OR approved_amount > 0', name='ck_support_requests_approved_amount_positive'),
    sa.CheckConstraint('requested_amount > 0', name='ck_support_requests_requested_amount_positive'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requesting_agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supporting_agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_provider_id'), 'support_requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_support_requests_requesting_agent_id'), 'support_requests', ['requesting_agent_id'], unique=False)
    op.create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    op.create_index(op.f('ix_support_requests_supporting_agent_id'), 'support_requests', ['supporting_agent_id'], unique=False)
    op.create_table('support_request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('actor_code', sa.String(length=100), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('created', 'accepted', 'rejected', 'escalated', 'resolved', 'cancelled', 'note_added')", name='ck_support_request_events_type'),
    sa.ForeignKeyConstraint(['support_request_id'], ['support_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_request_events_created_at'), 'support_request_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_request_events_event_type'), 'support_request_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_support_request_events_support_request_id'), 'support_request_events', ['support_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_request_events_support_request_id'), table_name='support_request_events')
    op.drop_index(op.f('ix_support_request_events_event_type'), table_name='support_request_events')
    op.drop_index(op.f('ix_support_request_events_created_at'), table_name='support_request_events')
    op.drop_table('support_request_events')
    op.drop_index(op.f('ix_support_requests_supporting_agent_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_requesting_agent_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_provider_id'), table_name='support_requests')
    op.drop_table('support_requests')
    # ### end Alembic commands ###
