"""add alert tables

Revision ID: a6b3aa69e3a2
Revises: 54a7192c8409
Create Date: 2026-07-11 23:00:08.077151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b3aa69e3a2'
down_revision: Union[str, Sequence[str], None] = '54a7192c8409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_bn', sa.Text(), nullable=False),
    sa.Column('title_bn_latn', sa.Text(), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('message_bn', sa.Text(), nullable=False),
    sa.Column('message_bn_latn', sa.Text(), nullable=False),
    sa.Column('next_step_en', sa.Text(), nullable=False),
    sa.Column('next_step_bn', sa.Text(), nullable=False),
    sa.Column('next_step_bn_latn', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('freshness_state', sa.String(length=30), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('automatic_action_taken', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("alert_type IN ('LIQUIDITY_RUNWAY', 'ANOMALY_REVIEW', 'STALE_DATA', 'SERVICEABILITY_SHORTFALL')", name='ck_alerts_alert_type'),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'ASSIGNED', 'ESCALATED', 'RESOLVED')", name='ck_alerts_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_alerts_confidence'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_index('ix_alerts_agent_status_created_at', 'alerts', ['agent_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_alerts_scenario_id', 'alerts', ['scenario_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_events_alert_created_at', 'alert_events', ['alert_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_alert_created_at', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_alerts_scenario_id', table_name='alerts')
    op.drop_index('ix_alerts_agent_status_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
