"""add core liquidity tables

Revision ID: bca30d05018c
Revises: 6c1c71ad7557
Create Date: 2026-07-11 16:32:34.703012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca30d05018c'
down_revision: Union[str, Sequence[str], None] = '6c1c71ad7557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_table('agent_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('shared_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('shared_cash >= 0', name='ck_agent_positions_shared_cash_nonnegative'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_positions_agent_id'), 'agent_positions', ['agent_id'], unique=True)
    op.create_table('provider_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('electronic_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('freshness_state', sa.String(length=20), server_default='fresh', nullable=False),
    sa.CheckConstraint("freshness_state IN ('fresh', 'delayed', 'missing', 'conflicting')", name='ck_provider_balances_freshness_state'),
    sa.CheckConstraint('electronic_balance >= 0', name='ck_provider_balances_nonnegative'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'provider_id', name='uq_provider_balances_agent_provider')
    )
    op.create_index(op.f('ix_provider_balances_agent_id'), 'provider_balances', ['agent_id'], unique=False)
    op.create_index(op.f('ix_provider_balances_provider_id'), 'provider_balances', ['provider_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=False),
    sa.Column('scenario_id', sa.String(length=60), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('synthetic_customer_id', sa.String(length=60), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('anomaly_expected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('anomaly_category', sa.String(length=50), nullable=True),
    sa.Column('injection_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('cash_in', 'cash_out')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_agent_id'), 'transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_provider_id'), 'transactions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_transactions_scenario_id'), 'transactions', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_scenario_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_agent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_provider_balances_provider_id'), table_name='provider_balances')
    op.drop_index(op.f('ix_provider_balances_agent_id'), table_name='provider_balances')
    op.drop_table('provider_balances')
    op.drop_index(op.f('ix_agent_positions_agent_id'), table_name='agent_positions')
    op.drop_table('agent_positions')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
