"""add agent coordinates

Revision ID: c6e6c2a36199
Revises: bca30d05018c
Create Date: 2026-07-11 19:00:00.434934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e6c2a36199'
down_revision: Union[str, Sequence[str], None] = 'bca30d05018c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('agents', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.drop_constraint(op.f('agents_code_key'), 'agents', type_='unique')
    op.create_index(op.f('ix_agents_code'), 'agents', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_code'), table_name='agents')
    op.create_unique_constraint(op.f('agents_code_key'), 'agents', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('agents', 'longitude')
    op.drop_column('agents', 'latitude')
    # ### end Alembic commands ###
